### ISSUE TITLE
Expose the Node, Element and Text classes

### ISSUE THREAD

**Issue by olstenlarck** [developit/undom#12]
It would be great. I seen the discussion about plugins in opened issues. But this one would be great too, because we'll be able to create hyperscript function using this classes directly and so Virtual DOM nodes would be just almost the same as the real dom nodes.

**Comment by developit** [comment]
They are exposed:

```js
import undom from 'undom';

let document = undom();

let { Node, Text, Element } = document.defaultView;
```
