### ISSUE TITLE
event.target should match event.currentTarget at time of dispatch

### ISSUE THREAD

**Issue by leeoniya** [developit/undom#18]
https://github.com/developit/undom/blob/master/src/undom.js#L140

should be

```js
let t = event.currentTarget = event.target = this,
```

**Comment by leeoniya** [comment]
err, no i think this is wrong too.

`currentTarget` always points to the element the listener is attached to while `target` is the source of the event.

the actual impl that passes my browser-tested tests is this one:

```js
Element.prototype.dispatchEvent = function(event) {
	let t = event.target = this,
		c = event.cancelable,
		l, i;
	do {
		l = t.__handlers && t.__handlers[(event.type).toLowerCase()];
		if (l && (event.currentTarget = t)) for (i=l.length; i--; ) {
			if ((l[i].call(t, event)===false || event._end) && c) break;
		}
	} while (event.bubbles && !(c && event._stop) && (t=t.parentNode));
	return !event.defaultPrevented;
};
```

**Comment by developit** [comment]
That is correct, yes.

**Comment by leeoniya** [comment]
FWIW, i had to make some other additions/tweaks to undom to get all my tests fully working (that already passed in browsers), though i cannot guarantee my impls are anything close to DOM spec compliant :D

feel free to cherry pick anything you find useful.

https://github.com/leeoniya/domvm/blob/3.x-dev/test/init-spec.js

**Comment by developit** [comment]
Whoops, had those properties reversed!
