### ISSUE TITLE
new release, please?

### ISSUE THREAD

**Issue by zaceno** [developit/undom#20]
Hi!

Could we have a new release of undom, so the latest commits since a few months are available via npm install?

In particular, I'd like to begin using undom for testing with Hyperapp, which requires 92c9808d981d72ba300657e2ae51aef63602814b

Thanks!

**Comment by developit** [comment]
Yes!

**Comment by leeoniya** [comment]
hopefully with #17 and #18 ;)

**Comment by developit** [comment]
Done. [0.4.0](https://github.com/developit/undom/releases/tag/0.4.0) includes those fixes for dispatchEvent().

**Comment by zaceno** [comment]
Awesomesauce!
