### ISSUE TITLE
Support SVGElement

### ISSUE THREAD

**Issue by tkh44** [developit/undom#4]
Now that preact checks for `instanceof SVGElement` you are unable to test preact components using undom.

https://github.com/developit/preact/blob/fd4f21f5c45dfd75151bd27b4c217d8003aa5eb9/src/vdom/diff.js#L37

**Comment by developit** [comment]
Ahh - I had left this out because I wanted undom to treat SVG elements as regular elements, but I realize now this would throw because SVGElement would then be undefined.  Perhaps undom can just export SVGElement as an alias of Element (thus making it global when pulled in via the polyfill).

**Comment by tkh44** [comment]
I wasn't sure how to accomplish this either because of the straight call to SVGElement from window.

**Comment by developit** [comment]
The polyfill installs everything from `document.defaultView` as globals, so just adding the alias should make it a global as well.

**Comment by developit** [comment]
Let me know if you're able to test that this fixed things for you! :)

**Comment by tkh44** [comment]
Ok will do

**Comment by tkh44** [comment]
Tested and working!

I just did `Object.assign(global, undom())`. Is this the method you would use?

**Comment by developit** [comment]
That's basically all the polyfill does, just a little easier to type:

```js
import 'undom/register';
// or
require('undom/register');
```

**Comment by developit** [comment]
I'll cut a release with this fix ASAP. Working on a V2 though ;)
